FROM mcr.microsoft.com/playwright:v1.41.1-jammy as builder
ENV PNPM_HOME="/pnpm"
ENV PATH="$PNPM_HOME:$PATH"
RUN corepack enable

# Set working directory
COPY ./ /app
WORKDIR /app

# install
RUN pnpm install --frozen-lockfile
RUN pnpm build

# Run tests
CMD ["bash", "-c", "pnpm run serve-storybook & pnpm run test"]