name: PrPreview

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "master" branch
  pull_request:
    branches: ["master"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  example_comment_pr:
    runs-on: ubuntu-latest
    name: An example job to comment a PR
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Comment Pull Request
        uses: thollander/actions-comment-pull-request@v1.4.1
        with:
          message: |
            Frontend for this PR will be available for testing here: https://design-system-pr-${{github.event.number}}.staging.giosg.com
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
